### ISSUE TITLE
사용자 등록 부분 버그 

### ISSUE THREAD

**Issue by SulimChoi** [pgrm-study-website/Backend#10]
정상 social 값: 0, 1, 2

social 값이 4 이상으로 입력했을 때는 내부 서버 오류라고 뜨는데, 3으로 입력하면 오류 없이 값이 들어가네요.. 이 부분 확인 부탁드립니다~

**Comment by SulimChoi** [comment]
해결하시고 commit 남기실 때 

![image](https://user-images.githubusercontent.com/66582313/161666857-b50499f5-4ef9-42e2-bd34-3ae11a38b73d.png)

commit message에 사진처럼 추가해서 남겨주세요!

**Comment by JMsuper** [comment]
일단, social값은 0,1,2,3이 정상이 맞습니다.(0 : 이메일 회원가입, 1 : 구글, 2 : 카카오, 3 : 깃허브)
추가적으로, 클라이언트가 처음으로 소셜 로그인을 할 때, 추가적인 회원가입을 진행하지 않고,
서버에서 바로 회원가입을 진행시키도록 프론트엔드분과 정하였습니다. 소셜 로그인을 한 회원정보는
소셜 로그인 인증을 통해 서버에서 얻어올 수 있으며, 해당 정보로 서버에서 회원가입을 진행시킬 예정입니다.

현재 500 error는 User Entity에서 validation을 체크하는 부분에서 발생하고 있습니다. 추후 controller에 정상적으로 validatioin을 넣었다면, 500 error는 서버에서 잘못된 로직을 작성하여 발생하는 오류일 것입니다.

다만, validation체크의 경우, 정상 응답을 해주는 api를 작성한 이후에 부족한 부분들을 한꺼번에 추가하는 것이 좋을 것 같은데, 어떻게 생각하시는지 답변부탁드립니다.

**Comment by SulimChoi** [comment]
네! 한 번에 추가하는 것이 좋을 것 같아요
